const express = require("express");
const app = express();
const PORT = process.env.PORT || 3001;

app.get("/data", (request, responce) => {
  responce.json([
    {
      id: "1000",
      inventary_number: "f230fh0g3",
      name: "Bamboo Watch",
      description: "Product Description",
      image: "bamboo-watch.jpg",
      price: 65,
      category: "Accessories",
      quantity: 24,
      inventoryStatus: "INSTOCK",
      rating: 5,
    },
    {
      id: "1001",
      inventary_number: "nvklal433",
      name: "Black Watch",
      description: "Product Description",
      image: "black-watch.jpg",
      price: 72,
      category: "Accessories",
      quantity: 61,
      inventoryStatus: "INSTOCK",
      rating: 4,
    },
    {
      id: "1002",
      inventary_number: "zz21cz3c1",
      name: "Blue Band",
      description: "Product Description",
      image: "blue-band.jpg",
      price: 79,
      category: "Fitness",
      quantity: 2,
      inventoryStatus: "LOWSTOCK",
      rating: 3,
    },
    {
      id: "1003",
      inventary_number: "244wgerg2",
      name: "Blue T-Shirt",
      description: "Product Description",
      image: "blue-t-shirt.jpg",
      price: 29,
      category: "Clothing",
      quantity: 25,
      inventoryStatus: "INSTOCK",
      rating: 5,
    },
    {
      id: "1004",
      inventary_number: "h456wer53",
      name: "Bracelet",
      description: "Product Description",
      image: "bracelet.jpg",
      price: 15,
      category: "Accessories",
      quantity: 73,
      inventoryStatus: "INSTOCK",
      rating: 4,
    },
    {
      id: "1005",
      inventary_number: "av2231fwg",
      name: "Brown Purse",
      description: "Product Description",
      image: "brown-purse.jpg",
      price: 120,
      category: "Accessories",
      quantity: 0,
      inventoryStatus: "OUTOFSTOCK",
      rating: 4,
    },
    {
      id: "1006",
      inventary_number: "bib36pfvm",
      name: "Chakra Bracelet",
      description: "Product Description",
      image: "chakra-bracelet.jpg",
      price: 32,
      category: "Accessories",
      quantity: 5,
      inventoryStatus: "LOWSTOCK",
      rating: 3,
    },
    {
      id: "1007",
      inventary_number: "mbvjkgip5",
      name: "Galaxy Earrings",
      description: "Product Description",
      image: "galaxy-earrings.jpg",
      price: 34,
      category: "Accessories",
      quantity: 23,
      inventoryStatus: "INSTOCK",
      rating: 5,
    },
    {
      id: "1008",
      inventary_number: "vbb124btr",
      name: "Game Controller",
      description: "Product Description",
      image: "game-controller.jpg",
      price: 99,
      category: "Electronics",
      quantity: 2,
      inventoryStatus: "LOWSTOCK",
      rating: 4,
    },
    {
      id: "1009",
      inventary_number: "cm230f032",
      name: "Gaming Set",
      description: "Product Description",
      image: "gaming-set.jpg",
      price: 299,
      category: "Electronics",
      quantity: 63,
      inventoryStatus: "INSTOCK",
      rating: 3,
    },
    {
      id: "1010",
      inventary_number: "plb34234v",
      name: "Gold Phone Case",
      description: "Product Description",
      image: "gold-phone-case.jpg",
      price: 24,
      category: "Accessories",
      quantity: 0,
      inventoryStatus: "OUTOFSTOCK",
      rating: 4,
    },
    {
      id: "1011",
      inventary_number: "4920nnc2d",
      name: "Green Earbuds",
      description: "Product Description",
      image: "green-earbuds.jpg",
      price: 89,
      category: "Electronics",
      quantity: 23,
      inventoryStatus: "INSTOCK",
      rating: 4,
    },
    {
      id: "1012",
      inventary_number: "250vm23cc",
      name: "Green T-Shirt",
      description: "Product Description",
      image: "green-t-shirt.jpg",
      price: 49,
      category: "Clothing",
      quantity: 74,
      inventoryStatus: "INSTOCK",
      rating: 5,
    },
    {
      id: "1013",
      inventary_number: "fldsmn31b",
      name: "Grey T-Shirt",
      description: "Product Description",
      image: "grey-t-shirt.jpg",
      price: 48,
      category: "Clothing",
      quantity: 0,
      inventoryStatus: "OUTOFSTOCK",
      rating: 3,
    },
    {
      id: "1014",
      inventary_number: "waas1x2as",
      name: "Headphones",
      description: "Product Description",
      image: "headphones.jpg",
      price: 175,
      category: "Electronics",
      quantity: 8,
      inventoryStatus: "LOWSTOCK",
      rating: 5,
    },
    {
      id: "1015",
      inventary_number: "vb34btbg5",
      name: "Light Green T-Shirt",
      description: "Product Description",
      image: "light-green-t-shirt.jpg",
      price: 49,
      category: "Clothing",
      quantity: 34,
      inventoryStatus: "INSTOCK",
      rating: 4,
    },
    {
      id: "1016",
      inventary_number: "k8l6j58jl",
      name: "Lime Band",
      description: "Product Description",
      image: "lime-band.jpg",
      price: 79,
      category: "Fitness",
      quantity: 12,
      inventoryStatus: "INSTOCK",
      rating: 3,
    },
    {
      id: "1017",
      inventary_number: "v435nn85n",
      name: "Mini Speakers",
      description: "Product Description",
      image: "mini-speakers.jpg",
      price: 85,
      category: "Clothing",
      quantity: 42,
      inventoryStatus: "INSTOCK",
      rating: 4,
    },
    {
      id: "1018",
      inventary_number: "09zx9c0zc",
      name: "Painted Phone Case",
      description: "Product Description",
      image: "painted-phone-case.jpg",
      price: 56,
      category: "Accessories",
      quantity: 41,
      inventoryStatus: "INSTOCK",
      rating: 5,
    },
    {
      id: "1019",
      inventary_number: "mnb5mb2m5",
      name: "Pink Band",
      description: "Product Description",
      image: "pink-band.jpg",
      price: 79,
      category: "Fitness",
      quantity: 63,
      inventoryStatus: "INSTOCK",
      rating: 4,
    },
    {
      id: "1020",
      inventary_number: "r23fwf2w3",
      name: "Pink Purse",
      description: "Product Description",
      image: "pink-purse.jpg",
      price: 110,
      category: "Accessories",
      quantity: 0,
      inventoryStatus: "OUTOFSTOCK",
      rating: 4,
    },
    {
      id: "1021",
      inventary_number: "pxpzczo23",
      name: "Purple Band",
      description: "Product Description",
      image: "purple-band.jpg",
      price: 79,
      category: "Fitness",
      quantity: 6,
      inventoryStatus: "LOWSTOCK",
      rating: 3,
    },
    {
      id: "1022",
      inventary_number: "2c42cb5cb",
      name: "Purple Gemstone Necklace",
      description: "Product Description",
      image: "purple-gemstone-necklace.jpg",
      price: 45,
      category: "Accessories",
      quantity: 62,
      inventoryStatus: "INSTOCK",
      rating: 4,
    },
    {
      id: "1023",
      inventary_number: "5k43kkk23",
      name: "Purple T-Shirt",
      description: "Product Description",
      image: "purple-t-shirt.jpg",
      price: 49,
      category: "Clothing",
      quantity: 2,
      inventoryStatus: "LOWSTOCK",
      rating: 5,
    },
    {
      id: "1024",
      inventary_number: "lm2tny2k4",
      name: "Shoes",
      description: "Product Description",
      image: "shoes.jpg",
      price: 64,
      category: "Clothing",
      quantity: 0,
      inventoryStatus: "INSTOCK",
      rating: 4,
    },
    {
      id: "1025",
      inventary_number: "nbm5mv45n",
      name: "Sneakers",
      description: "Product Description",
      image: "sneakers.jpg",
      price: 78,
      category: "Clothing",
      quantity: 52,
      inventoryStatus: "INSTOCK",
      rating: 4,
    },
    {
      id: "1026",
      inventary_number: "zx23zc42c",
      name: "Teal T-Shirt",
      description: "Product Description",
      image: "teal-t-shirt.jpg",
      price: 49,
      category: "Clothing",
      quantity: 3,
      inventoryStatus: "LOWSTOCK",
      rating: 3,
    },
    {
      id: "1027",
      inventary_number: "acvx872gc",
      name: "Yellow Earbuds",
      description: "Product Description",
      image: "yellow-earbuds.jpg",
      price: 89,
      category: "Electronics",
      quantity: 35,
      inventoryStatus: "INSTOCK",
      rating: 3,
    },
    {
      id: "1028",
      inventary_number: "tx125ck42",
      name: "Yoga Mat",
      description: "Product Description",
      image: "yoga-mat.jpg",
      price: 20,
      category: "Fitness",
      quantity: 15,
      inventoryStatus: "INSTOCK",
      rating: 5,
    },
    {
      id: "1029",
      inventary_number: "gwuby345v",
      name: "Yoga Set",
      description: "Product Description",
      image: "yoga-set.jpg",
      price: 20,
      category: "Fitness",
      quantity: 25,
      inventoryStatus: "INSTOCK",
      rating: 8,
    },
  ]);
});

app.listen(PORT, () => {
  console.log(`Server is starting on PORT ${PORT}`);
});
